### PR TITLE
25 hyper optimization

### PR DESCRIPTION
**Pull request by rogemus**
https://github.com/rogemus/rogemus.github.io/issues/25

### CODE REVIEW

**Comment by rogemus** [comment]
## Before:
styles.css: 6.52 KB
index.html: 16.27 KB

## After changes:
index.html: 14.7 KB
styles.min.css 5.15 KB (css was not minified before). But added styles for codeblock, toc

**Comment by rogemus** [comment]
## After removing unused vars
styles.min.css 4.96 KB

**Comment by kacper-rogowski-wttech** [comment]
## Remove custom fonts 
- ~800 kb

**Comment by rogemus** [comment]
## Remove custom fonts 
- ~800 kb

**Pull request merged**
